spring:
  datasource:
    url: jdbc:mysql://localhost/fj27_spring?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: caelum
  jpa:    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect   
